### ISSUE TITLE
Bioconda

### ISSUE THREAD

**Issue by muslih14** [zheminzhou/SPARSE#1]
Greetings SPARSE developers,

Congratulations on a fantastic tool. I think it will very useful for the metagenomic analysis community. I'd like to know if you've considered adding this tool to the bioconda package suite.

Best wishes,
Muslih.

**Comment by happykhan** [comment]
Hi, 

That's a great idea. I've never packaged for bioconda for, any tips?

**Comment by druvus** [comment]
I am happy to assist you with help how to do it. I think one of the first thing would be to package SPARSE as a Python module instead of separate scripts. Or at least include sparse in the filenames of run scripts.

**Comment by nick-youngblut** [comment]
I just added `sparse` to bioconda ([here's the PR](https://github.com/bioconda/bioconda-recipes/pull/9136)). The testing is minimal, but at least there's now a recipe.
