### ISSUE TITLE
Python3 compatibility ?

### ISSUE THREAD

**Issue by UriaMorP** [zheminzhou/SPARSE#2]
Hey there,
I installed SPARSE using the following commands:
```bash
conda create -n sparse python=3.6
source activate sparse
python -m pip install meta-sparse
```

The installation finished successfully, but then, when I try to run `sparse` I get Python 2 related errors (such as: the print function in line 113 of SPARSE.py is being used without brackets etc.)

Do you have any suggestions?

Since all of my other tools are in python $ \geq  3.5 $ I'm trying to avoid working with Python 2.

**Comment by nick-youngblut** [comment]
Yeah, it would be very helpful to state in the README that `SPARSE` is only py2.7 compatible. Currently, the `setup.py` includes:

```
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
```

... but the `.travis.yml` is only testing py2.7 and the code is obviously formatted for py2.7.

**Comment by zheminzhou** [comment]
Many thanks. I have now remove its compatiblity to only 2.7.

**Comment by UriaMorP** [comment]
Python3 port anytime soon?

**Comment by UriaMorP** [comment]
also, can you make sure that also the README file says python 2.7 (instead of >= 2.7)?

Do you have a development roadmap somewhere so I can find stuff I can help with?
