### ISSUE TITLE
RefSeq download instructions not working 

### ISSUE THREAD

**Issue by nick-youngblut** [zheminzhou/SPARSE#4]
At least for my Ubuntu 16.04.4 system, the instructions for downloading the pre-compiled RefSeq database:

```
curl -O refseq_20180531.tar.gz http://enterobase.warwick.ac.uk/sparse/refseq_20180531.tar.gz
tar -vxzf refseq_20180531.tar.gz
```

...doesn't work. It appears that the link is broken. This link does work: http://enterobase.warwick.ac.uk/sparse/refseq_20180519.tar.gz

**Comment by zheminzhou** [comment]
Okey, I mistake. Many thanks. I have updated the link to http://enterobase.warwick.ac.uk/sparse/refseq_20180519.tar.gz.
